### ISSUE TITLE
RFC/Feature request: Automation of Ivy Compatibility Upgrades for Angular Libraries

### ISSUE THREAD

**Issue by Jordan-Hall** [danielglejzner/ng16-dep-audit#4]
#### Summary
This RFC proposes an enhancement to the `ng16-dep-audit` tool, designed to facilitate the Angular 16 upgrade process for enterprise-level projects. The enhancement focuses on automating the detection of non-Ivy compatible libraries, creating issues, and submitting PRs to a centralized mono-repo for upgrading these libraries to Ivy compatibility.

#### Motivation
The transition to Angular 16, which requires Ivy compatibility, presents a significant challenge for many projects, especially those reliant on libraries that have not yet adopted Ivy. Manual identification and updating of these libraries are time-consuming and error-prone. This proposal aims to streamline this process, reducing the overhead for developers and speeding up the upgrade path.

#### Detailed Design

- **Automated Library Detection**: `ng16-dep-audit` will include a mechanism to automatically detect any dependencies that are not Ivy compatible.
- **Issue and PR Automation**:
    - For each detected non-Ivy compatible library, the tool will automatically open an issue in a designated GitHub repository.
    - The issue will detail the package name, author, author email, and git URL (if available).
    - Simultaneously, `ng16-dep-audit` will generate a PR against a mono-repo, attempting to upgrade the library to Ivy compatibility using the standard `ng update` process.
- **Mono-Repo Management**:
    - A mono-repo under NG Upgrade repo will be established to centralize the Ivy upgrade efforts. This repo will host the upgraded versions of non-Ivy libraries.
    - The repo will utilize Nx (or similar tools) for managing library versions and dependencies, ensuring an efficient upgrade path as Angular versions progress.

#### New Flag for `ng16-dep-audit`
- A new flag `--auto-migrate` will be introduced to `ng16-dep-audit`. When enabled, this flag will trigger the automatic migration of the library package name to the new one hosted in the mono-repo, ensuring projects can easily switch to the upgraded libraries.

#### Disclaimer and NPM Warning
Upon using `ng16-dep-audit` with the proposed enhancements, users will be presented with a disclaimer and an NPM warning stating:
- The automated upgrade process is primarily intended to facilitate the transition to Angular 16 and beyond, without extensive refactoring.
- The mono-repo's focus is to provide Ivy compatibility upgrades without introducing new features or fixing existing issues outside of migration needs.
- Users are advised that the upgraded libraries are meant as a temporary solution on the upgrade path. They should plan to transition to officially supported versions as they become available.

#### Adoption and Implementation Strategy
- **Community Involvement**: Invite contributions from the Angular community to assist in the upgrade efforts, especially for widely used libraries.
- **Continuous Integration**: Set up CI processes within the mono-repo to automatically test library upgrades against the latest Angular versions, ensuring compatibility and easing maintenance burdens.

#### Open Questions
- How will library authors be involved in the process, and how can we ensure the upgrades align with their plans for Ivy compatibility?
- What mechanisms will be in place to deprecate mono-repo libraries as their official versions become Ivy compatible?

#### Conclusion
The proposed enhancements to `ng16-dep-audit` aim to significantly reduce the friction associated with upgrading to Angular 16 by providing automated tools to identify and upgrade non-Ivy compatible libraries. This initiative will help maintain the Angular ecosystem's health and assist enterprise projects in staying up-to-date with the latest Angular advancements.

**Comment by ghost** [comment]
@Jordan-Hall can I put this on my plate❓ This challenges me 😆

**Comment by Jordan-Hall** [comment]
It would require collaboration I think but happy to let you take lead. I think it be a big mono repo hopefully one that runs ng update and let us know when it fails too. Obviously not this repo.

**Comment by danielglejzner** [comment]
@NgDaddy @Jordan-Hall 

Let's do it here :) https://github.com/danielglejzner/ngx-maintanance

Great name suggestion @Jordan-Hall btw

**Comment by ghost** [comment]
@danielglejzner, ok, let's continue on there :)
