### ISSUE TITLE
Display version issue

### ISSUE THREAD

**Issue by Jordan-Hall** [danielglejzner/ng16-dep-audit#5]
Currently this is hard coded. When this was added the repo wasn't checked out. I'm not sure if we can include the package.json dynamically without a build step.

https://github.com/danielglejzner/ng16-dep-audit/blob/88baf920376e2e640aff37932000d70012bf3ca1/index.js#L30

Ideally don't want to add nom package or build step to the project but this should be automated.

**Comment by ghost** [comment]
It sounds like it is asking for having typescript and a build step, isn't it? :)

**Comment by Jordan-Hall** [comment]
I'm saying not too

**Comment by Jordan-Hall** [comment]
Want to keep it build free. Maybe it can read packages.json not tested it

**Comment by ghost** [comment]
#6 I've proposed this PR with reading the version as well

**Comment by Jordan-Hall** [comment]
Merger and closed :) thank you
